site_name: RiskFlow

theme: readthedocs

nav:
    - Home: index.md
    - Requirements: require.md
    - Theory:
        - 'Definitions': 'Theory/Definitions.md'
        - 'Asset Pricing': 'Theory/Asset_Pricing.md'
        - 'Energy Pricing': 'Theory/Energy_Pricing.md'
        - 'Interest Rates': 'Theory/Interest_Rates.md'
        - 'Survival Rates': 'Theory/Survival_Rates.md'
        - 'Inflation': 'Theory/Inflation.md'
    - Valuation:
        - 'Definitions': 'Valuation/Definitions.md'
        - 'FX and Equity': 'Valuation/FX_and_Equity.md'
        - 'Energy': 'Valuation/Energy.md'
        - 'Interest Rates': 'Valuation/Interest_Rates.md'
        - 'Credit': 'Valuation/Credit.md'
        - 'Inflation': 'Valuation/Inflation.md'
        - 'Collateral': 'Valuation/Collateral.md'
    - Boostrapping:
        - 'General': 'Boostrapping/General.md'
        - 'FX and Equity': 'Boostrapping/FX_and_Equity.md'
        - 'Interest Rates': 'Boostrapping/Interest_Rates.md'
    - API:
        - 'Data': 'API/Data.md'
        - 'Calculations': 'API/Calculations.md'
        - 'Examples': 'API/Examples.md'
    - JSON Structures:
        - 'General': 'JSON/General.md'
        - 'FX and Equity': 'JSON/FX_and_Equity.md'
        - 'Energy': 'JSON/Energy.md'
        - 'Interest Rates': 'JSON/Interest_Rates.md'
        - 'Inflation': 'JSON/Inflation.md'
        - 'Credit': 'JSON/Credit.md'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True